# Generated by Django 5.1.1 on 2024-10-07 15:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A_Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('numero_identificacao', models.CharField(max_length=10, unique=True)),
                ('turno', models.CharField(max_length=50)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='B_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='C_Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto')])),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppEstacionaPlus.b_cliente')),
            ],
        ),
        migrations.CreateModel(
            name='D_EntradaVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(default=django.utils.timezone.now)),
                ('hora_entrada', models.TimeField(default=django.utils.timezone.now)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEstacionaPlus.a_funcionario')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEstacionaPlus.c_veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='E_SaidaVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateField(default=django.utils.timezone.now)),
                ('hora_saida', models.TimeField(default=django.utils.timezone.now)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEstacionaPlus.a_funcionario')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEstacionaPlus.c_veiculo')),
            ],
        ),
    ]
