# Generated by Django 5.1.1 on 2024-10-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEstacionaPlus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_funcionario',
            name='numero_identificacao',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='a_funcionario',
            name='turno',
            field=models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')]),
        ),
        migrations.AlterField(
            model_name='c_veiculo',
            name='tipo',
            field=models.CharField(choices=[('Carro', 'Carro'), ('Moto', 'Moto')]),
        ),
    ]
