# Generated by Django 5.1.1 on 2024-10-04 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEstacionaPlus', '0003_remove_entradaveiculo_data_hora_entrada_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcionario',
            new_name='A_Funcionario',
        ),
        migrations.RenameModel(
            old_name='Cliente',
            new_name='B_Cliente',
        ),
        migrations.RenameModel(
            old_name='Veiculo',
            new_name='C_Veiculo',
        ),
        migrations.RenameModel(
            old_name='SaidaVeiculo',
            new_name='D_EntradaVeiculo',
        ),
        migrations.RenameModel(
            old_name='EntradaVeiculo',
            new_name='E_SaidaVeiculo',
        ),
        migrations.RenameField(
            model_name='d_entradaveiculo',
            old_name='data_saida',
            new_name='data_entrada',
        ),
        migrations.RenameField(
            model_name='d_entradaveiculo',
            old_name='hora_saida',
            new_name='hora_entrada',
        ),
        migrations.RenameField(
            model_name='e_saidaveiculo',
            old_name='data_entrada',
            new_name='data_saida',
        ),
        migrations.RenameField(
            model_name='e_saidaveiculo',
            old_name='hora_entrada',
            new_name='hora_saida',
        ),
    ]
