# Generated by Django 5.1.1 on 2024-11-29 15:13

import AppEstacionaPlus.models
import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEstacionaPlus', '0003_a_funcionario_foto_alter_a_funcionario_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('CPF', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('CPF', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail')),
                ('numero_identificacao', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('turno', models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=5, verbose_name='Turno')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=AppEstacionaPlus.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
        migrations.RemoveField(
            model_name='d_entradaveiculo',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='e_saidaveiculo',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='c_veiculo',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='e_saidaveiculo',
            name='veiculo',
        ),
        migrations.RemoveField(
            model_name='d_entradaveiculo',
            name='veiculo',
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('placa', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True, verbose_name='Placa')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('cor', models.CharField(max_length=30, verbose_name='Cor')),
                ('tipo', models.CharField(choices=[('Carro', 'Carro'), ('Moto', 'Moto')], verbose_name='Tipo')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppEstacionaPlus.cliente')),
            ],
            options={
                'verbose_name': 'Veiculo',
                'verbose_name_plural': 'Veiculos',
            },
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEstacionaPlus.funcionario')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEstacionaPlus.veiculo')),
            ],
            options={
                'verbose_name': 'Saida',
                'verbose_name_plural': 'Saidas',
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEstacionaPlus.funcionario')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEstacionaPlus.veiculo')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
            },
        ),
        migrations.DeleteModel(
            name='A_Funcionario',
        ),
        migrations.DeleteModel(
            name='B_Cliente',
        ),
        migrations.DeleteModel(
            name='E_SaidaVeiculo',
        ),
        migrations.DeleteModel(
            name='C_Veiculo',
        ),
        migrations.DeleteModel(
            name='D_EntradaVeiculo',
        ),
    ]
